[package]
name = "sufr_bwt"
version = "0.0.1"
description = "Generates a Burrows-Sheeler transform from the sufr suffix array library, and implements the count() function."
license = "BSD-3-Clause"
repository = "https://github.com/UM-Applied-Algorithms-Lab/sufr_bwt"
authors = [
    "Tim Anderson <tim.anderson@umontana.edu"
]
edition = "2021"

[dependencies]
rayon = "1.10.0"
anyhow = "1.0.92"
libsufr = "0.3.0"
sufr = "0.3.1"
aligned-vec = "0.6.1"
aligned = "0.4.2"

[lib]
crate-type = ["lib"]
path = "src/lib.rs"

rustflags = ["-C", "target-cpu=native"]


