name: ChatGPT Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  automatic-gpt-code-review:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for accurate diffs

      - name: Debug File Changes
        run: git diff --name-only ${{ github.event.before }} ${{ github.sha }}
      
      - uses: anc95/ChatGPT-CodeReview@v1.0.19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # Optional
          LANGUAGE: English
          OPENAI_API_ENDPOINT: https://api.openai.com/v1
          MODEL: gpt-3.5-turbo # https://platform.openai.com/docs/models
          PROMPT: "Please check if there are any confusions or irregularities in the following code diff:"
          top_p: 1 # https://platform.openai.com/docs/api-reference/chat/create#chat/create-top_p
          temperature: 0.7 # https://platform.openai.com/docs/api-reference/chat/create#chat/create-temperature
          max_tokens: 20000
          MAX_PATCH_LENGTH: 10000 # if the patch/diff length is large than MAX_PATCH_LENGTH, will be ignored and won't review. By default, with no MAX_PATCH_LENGTH set, there is also no limit for the patch/diff length.
          IGNORE_PATTERNS: '*.md' # glob pattern or regex pattern to ignore files, separated by comma
          INCLUDE_PATTERNS: '**/*.rs,**/*.yaml,**/*.yml,**/*.toml,**/*.json,**/*.xml' # glob pattern or regex pattern to include files, separated by comma